
-- select * from customer limit 5;

-- Q1. What is the total revenue generated by male vs female customers?

select gender "Gender", sum(purchase_amount) "Total Revenue"
from customer
group by gender;


-- Q2. Which customers used a discount but still spent more than the average purchase amount?

select customer_id "Customer",
       discount_applied,
	   purchase_amount	
from customer 
where discount_applied='Yes' AND purchase_amount > (select avg(purchase_amount) from customer);


-- Q3. Which are the top 5 products with highest average review rating?

select item_purchased "Product",
       round(avg(review_rating)::numeric,2) "Average Review Rating"
from customer
group by item_purchased
order by round(avg(review_rating)::numeric,2) desc
limit 5;


-- Q4. Compare the average Purchase Amounts between Standard and Express Shipping?

select shipping_type,
       round(avg(purchase_amount),2) "Average Purchase Amount"
from customer
where shipping_type in ('Standard','Express')
group by shipping_type;


-- Q5. Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non-subscribers?

select subscription_status as subscription_type, 
       count(customer_id) as customers, 
	   round(avg(purchase_amount),2) as average_spend, 
	   round(sum(purchase_amount),2) as total_revenue
from customer
group by subscription_status
order by total_revenue, average_spend desc;


-- Q6. Which 5 products have the highest percentage of purchases with discounts applied?

select item_purchased, 
round(sum(case when discount_applied='Yes' then 1 else 0 end) * 100 / count(1),2) discount_rate
from customer
group by item_purchased
order by discount_rate desc
limit 5;


-- Q7. Segments customers into New, Returning and Loyal based on their total number of previous purchases, and show the count of each segment?

with customer_type as 
(
	select customer_id, 
	       previous_purchases,
	       case when previous_purchases = 1 then 'New'       
		        when previous_purchases between 2 and 10 then 'Returning'
				when previous_purchases > 10 then 'Loyal'
		   end customer_segment
    from customer
);

select customer_segment,
       count(customer_id) customer_count_segmentwise
from customer_type
group by customer_segment
order by customer_count_segmentwise desc;


-- Q8. What are the top 3 most purchased products within each category?

with rank_purchased as (
select category,
       item_purchased,
       count(customer_id),
	   ROW_NUMBER() over(partition by category order by count(customer_id) desc) rank_item_purchased	   
from customer
group by category,item_purchased
order by category
);

select category,
       item_purchased purchased_product
from rank_purchased
where rank_item_purchased <=3;


-- Q9. Are customers who are repeat buyers (more then 5 previous purchases) also likely to subcribe?

select subscription_status,
       count(customer_id) customer_count          
from customer
where previous_purchases > 5 
group by subscription_status
order by customer_count desc;



-- Q10. Waht is revenue contribution of each age group?

select age_group,
       sum(purchase_amount) revenue_contributions
from customer
group by age_group
order by revenue_contributions desc;

